# Generated by Django 4.2.21 on 2026-06-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('question_text', models.TextField()),
                ('choice1', models.CharField(max_length=255)),
                ('choice2', models.CharField(max_length=255)),
                ('choice3', models.CharField(max_length=255)),
                ('choice4', models.CharField(max_length=255)),
                ('correct_answer', models.IntegerField(choices=[(1, '1번'), (2, '2번'), (3, '3번'), (4, '4번')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
