# Generated by Django 4.2.21 on 2026-06-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_quiz_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, help_text='단답형일 때 정답', max_length=200, verbose_name='정답'),
        ),
    ]
