# Generated by Django 4.2.21 on 2026-07-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_question_image_question_video'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='questionattempt',
            constraint=models.UniqueConstraint(fields=('user', 'question'), name='unique_user_question_attempt'),
        ),
    ]
