# Generated by Django 4.2.21 on 2026-07-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_questionattempt_unique_user_question_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionattempt',
            name='first_attempt',
            field=models.BooleanField(default=False),
        ),
    ]
