# Generated by Django 4.2.21 on 2026-07-11 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_questionattempt_first_attempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionattempt',
            name='first_attempt',
        ),
    ]
