# Generated by Django 4.2.21 on 2026-07-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_remove_questionattempt_first_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
