# Generated by Django 4.2.21 on 2026-06-17 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_remove_question_user_alter_question_correct_answer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('likes', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='like',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.question'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'quiz')},
        ),
    ]
