# Generated by Django 4.2.21 on 2026-07-12 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_question_video_url'),
        ('likes', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='quizzes.question'),
        ),
    ]
