# Generated by Django 4.2.21 on 2026-07-08 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_questionattempt_user'),
        ('rankings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='quizzes.question'),
        ),
    ]
