# Generated by Django 4.2.21 on 2026-07-08 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0003_ranking_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
