# Generated by Django 4.2.21 on 2026-07-11 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0004_alter_ranking_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ranking',
        ),
    ]
